linters:
  enable:
  - asciicheck
  - bodyclose
  - deadcode
  - depguard
  - dogsled
  - errcheck
  - gochecknoinits
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godot
  - godox
  - goerr113
  - gofmt
  - goimports
  - golint
  - gomodguard
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - ineffassign
  - interfacer
  - maligned
  - misspell
  - nakedret
  - nestif
  - nolintlint
  - prealloc
  - rowserrcheck
  - scopelint
  - staticcheck
  - structcheck
  - stylecheck
  - typecheck
  - unconvert
  - unparam
  - unused
  - varcheck
  - whitespace
  disable:
  - dupl
  - funlen
  - gomnd
  - gochecknoglobals
  - testpackage
  - lll
  - wsl
