language: go

go:
        - 1.6.2

install:
        - go get github.com/d4l3k/messagediff
        - go get github.com/golang/lint/golint
        - go get github.com/twpayne/go-geom

script:
        - go test -v ./...
        - go test -cover -race ./...
        - go vet ./...
        - test -z "$(gofmt -d -s *.go)"
        - golint ./...

sudo: false
