language: go

env:
  global:
    - GO111MODULE=on

go:
  - 1.x
  - 1.12.x
  - 1.11.x

install: true

script:
        - go test -v ./...
        - go test -cover -race ./...
        - go vet ./...
        - test -z "$(gofmt -d -s *.go)"

sudo: false
