name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
env:
  GOTOOLCHAIN: local
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
      with:
        go-version: stable
    - name: build
      run: go build ./...
    - name: test
      run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
    - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32
      with:
        go-version: stable
    - uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86
      with:
        version: v1.59.1
