name: main
on:
  pull_request:
  push:
    branches:
    - master
    tags:
    - v*
env:
  GOTOOLCHAIN: local
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
      with:
        go-version: stable
    - name: build
      run: go build ./...
    - name: test
      run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
    - uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a
      with:
        go-version: stable
    - uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8
      with:
        version: v1.62.2
